title = "John W Hodson"
baseURL = "http://hodsonus.com/"
theme = "hugo-resume"
languageCode = "en-us"
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Seattle, WA"
email = "hodsonus@gmail.com"
favicon = "/redketchup/favicon.ico"
firstName = "John"
lastName = "Hodson"
phone = "(727)-348-2899"
profileImage = "/profile.jpg"
showEducation = true
showExperience = true
showOpenSource = false
showProjects = false
showPublications = false
showQr = true
showSkills = true

[[params.handles]]
link = "https://www.linkedin.com/in/hodsonus/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/hodsonus/"
name = "GitHub"

[[params.handles]]
link = "https://keybase.io/hodsonus/"
name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"